//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int VoteID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> DecisionID { get; set; }
        public Nullable<int> Vote1 { get; set; }
    
        public virtual Decision Decision { get; set; }
        public virtual User User { get; set; }
    }
}
