//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public User()
        {
            this.Votes = new HashSet<Vote>();
        }
    
        public int UserID { get; set; }
        
        public string UserFullName { get; set; }
        
        [Required(ErrorMessage = "Please provide user name ", AllowEmptyStrings = false)]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Please provide password", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string UserPassword { get; set; }

        public Nullable<bool> IsAdmin { get; set; }
    
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
